### ISSUE TITLE
Keyboard ScanDepth Issue

### ISSUE THREAD

**Issue by rishabhjain08** [KomodoOpenLab/TeclaAccess#40] opened 2012-03-25 12:45 UTC
Once I step into the keyboard i.e change scanDepth from DEPTH_ROW to DEPTH_KEY there is no way for me to step out without selecting a key.

**Comment by ijdoc** [comment] 2012-03-25 18:11
This issue is related to #17, we'll keep it open for now

**Comment by ijdoc** [comment] 2012-03-25 18:16
This is a duplicate of #20, will add the description as a comment on that issue. Any further comments should be added to #20

**Closed as completed by ijdoc** 2012-03-25 18:16 UTC
