### ISSUE TITLE
Always use speakerphone option not working on Galaxy Note 2

### ISSUE THREAD

**Issue by oranje** [KomodoOpenLab/TeclaAccess#203] opened 2013-04-15 16:15 UTC
Tecla Access 1.0
When always use speakerphone is checked incoming and outgoing still go through handset mic and speaker not speakerphone on Galaxy Note 2.

**Comment by ijdoc** [comment] 2013-04-15 16:20
@oranje was this working before on the same handset? I other words, is the error a result of the update?

**Comment by oranje** [comment] 2013-04-15 16:22
New installation from play store, no previous use of the Tecla Access app.

**Comment by sagar-chandarana** [comment] 2013-04-20 14:53
@oranje This issue has occurred before. #156 
At that time the speaker phone was not being activated only while placing the calls. Incoming calls were automatically transferred to the speaker. Please let us know if it happens the same in your case or it's completely a new issue.
@jorgesilva Is it occurring because of a code merge problem?

**Comment by ijdoc** [comment] 2013-04-22 00:16
@sagarchandarana123 not sure, but we need to confirm it first. Are you able to reproduce it on any of your devices? Would mind testing and posting the details?

**Comment by sagar-chandarana** [comment] 2013-04-22 01:27
In my experiences with different devices, it occurred only for the Android 4.1 and above. The reason is, JB automatically turns off the speaker when a new call is placed or received.

In detail: http://stackoverflow.com/questions/8791754/how-to-make-a-phone-call-with-speaker-on

Modifying some BroadcastReceivers is required as we have to first let JB turn off the speaker and then turn it on again. 

Assign this to me, I will look into it.

**Comment by sagar-chandarana** [comment] 2013-04-22 16:49
The issue is confirmed and it occurs because the Jellybean (com.android.phone.PhoneUtils.java) switches of speakerphone every time a call is attended (Incoming or outgoing). The 'call state' events are broadcast before this automation. So listening to different Intents doesn't work.

**Closed as completed** 2013-04-25 15:00 UTC
Labels: unconfirmed
